### ISSUE TITLE
Kontrolle Aufgabe 03

### ISSUE THREAD

**Issue by MelvinBusch** [RueJohannes/EIA2#1]
1. Die Skizze ist etwas knapp. Es sollten zur besseren Beschreibung noch die verwendeten HTML Elemente eingetragen sein.
2. Im AD werden Bedingungen immer in eckige Klammern geschrieben.
3. Die Verwendung der "Input-Knoten" ist nicht ganz richtig. Die Interaktionen des Nutzers sind nicht eindeutig einer Aktion im AD zuzuordnen. Besser wäre es für jede Interaktionsmöglichkeit ein eigenes AD mit dem "Input-Knoten" als Startpunkt und den entsprechenden Aktionen zu haben.
4. Das AD könnte etwas ausführlicher sein.
5. **Keine Umlaute in Funktions- oder Variablen Namen verwenden!!!**
6. Die Event-Listener könnten im Code etwas weiter oben stehen.
7. Code nicht funktionsfähig. Bevor Typescript auf den DOM zugreifen kann, muss gewartet werden, bis dieser auch vollständig geladen ist. Daher die Fehlermeldung auf der Konsole. Dafür eignet sich zum Beispiel der Event-Listender `DOMContentLoaded`. Du musst deinen Code noch etwas umstrukturieren.

_15.04 | 10:56 (mb)_

**Comment by Plagiatus** [comment]
> Das AD könnte etwas ausführlicher sein.
Das AD *muss* ausführlicher sein. Gerade die in dieser Aufgabe interessanten ADs sind nicht vorhanden.

**Comment by MelvinBusch** [comment]
Verteidigt. AD's werden nachgereicht.
